# Generated by Django 5.2.17 on 2026-09-20 13:27

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[recipes.models.validate_image_file]),
        ),
    ]
