# Generated by Django 5.2.17 on 2026-09-20 13:27

import django.core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Jumlah numerik untuk porsi standar (bisa kosong jika secukupnya)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/', validators=[recipes.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time_minutes',
            field=models.PositiveSmallIntegerField(help_text='Waktu masak dalam menit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='default_servings',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', validators=[recipes.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.PositiveSmallIntegerField(help_text='Waktu persiapan dalam menit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
